name: CI

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: windows-latest  # Choose the appropriate OS for your project

    steps:
    - uses: actions/checkout@v2  # Check out your repository

    - name: Set up CMake
      uses: cmake-actions/setup-cmake@v1
      with:
        cmake-version: '3.21'  # Adjust version as needed

    - name: Build and Package
      run: |
        cd third-party
        mkdir build
        cd build
        cmake ..
        cmake --build . --target package  # Generate installer
        # Add commands to upload the installer artifact (e.g., using GitHub Actions' upload-artifact)
